-- Connect to the Pluggable Database
ALTER SESSION SET CONTAINER = XEPDB1;

-- Create baton user in PDB
CREATE USER baton IDENTIFIED BY password;
GRANT DBA TO baton;
GRANT CREATE SESSION TO baton;
ALTER USER baton ACCOUNT UNLOCK;

-- Verify user creation
SELECT username, account_status FROM dba_users WHERE username = 'BATON';

-- Create test tables as baton
CONNECT baton/password@localhost:1521/XEPDB1;

-- Create users table
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) NOT NULL,
  email VARCHAR2(255),
  employee_id VARCHAR2(50),
  status VARCHAR2(20) DEFAULT 'active',
  account_type VARCHAR2(20) DEFAULT 'human',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login TIMESTAMP,
  manager_id NUMBER,
  password_hash VARCHAR2(255)
);

-- Insert test user
INSERT INTO users (username, email, employee_id) 
VALUES ('test_admin', 'admin@oracle.test', 'ORA001');

-- Show count
SELECT COUNT(*) as user_count FROM users;

COMMIT;
EXIT;