services:
  # MySQL Database for testing employee_id and last_login features
  mysql:
    image: mysql:8.0
    container_name: baton-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: batondb
      MYSQL_USER: baton
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./test/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "baton",
          "-ppassword",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
