services:
  # SQL Server Database for testing account provisioning and random password generation
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: baton-sqlserver-test
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - ./test/sqlserver-init.sql:/tmp/init.sql
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Simple init container to set up the database after SQL Server is ready
  sqlserver-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: baton-sqlserver-init
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - ./test/sqlserver-init.sql:/tmp/init.sql
    command: >
      /bin/bash -c "
        echo 'Initializing SQL Server database...'
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -C -Q 'CREATE DATABASE BatonTestDB'
        echo 'Database created, running initialization script...'
        /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P YourStrong@Passw0rd -C -d BatonTestDB -i /tmp/init.sql
        echo 'Database initialization complete!'
      "

volumes:
  sqlserver_data:
